version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_NAME="FastAPI Sales"
      - DEBUG_MODE=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=salesdb
      - CORS_ORIGINS=http://localhost:5173
    ports:
      - "8000:8000"
    entrypoint: ["sh", "/app/entrypoint.sh"]
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres:17.2-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesdb
    ports:
      - "5432:5432"
    volumes:
      - sales-leads-postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - sales-leads-pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  sales-leads-postgres_data:
  sales-leads-pgadmin_data:

networks:
  app-network:
    driver: bridge